### ISSUE TITLE
Submitting to wp.org

### ISSUE THREAD

**Issue by ideag** [gingersoulrecords/SoulMatch#1]
Hi, for submitting to WP.org there are a couple of things you would be better at doing, than I would:

1. Short description (up to 150 characters, no formatting)
1. Long description - can include links, bullet lists, bold/italic, etc. At least a couple paragraphs. A good place to mention your other plugins, including premium ones.
1. Logo and cover images - we discussed those before and they will only be needed after plugin is confirmed, but it is always good to have them ready.

P.S. is gsr username on wordpress.org yours? it seems to be registered but never used really used. If it is, could you give me access to that account - I'll do your submissions using it.

**Comment by gingersoulrecords** [comment]
1. Equalize the heights of any grouped element. A plugin powered by Liam Brummitt's excellent jquery-match-height script.

2. When you're showing grouped content in rows (e.g. blog posts, products, feature sets), it's almost inevitable that variations in content lengths will throw off your layout. 

SoulMatch helps you equalize the heights of your elements so that everything hangs together nicely, even when the page is resized. Simply provide a CSS selector (class, id, etc.) and the plugin will do the rest. 

[Plugin Assets.zip](https://github.com/gingersoulrecords/SoulMatch/files/801473/Plugin.Assets.zip)

**Comment by ideag** [comment]
https://wordpress.org/plugins/soulmatch/
